### ISSUE TITLE
1.9.0 v2 broken

### ISSUE THREAD

**Issue by Nillx** [butter-cookie-kitkat/ButterQuestTracker#45] opened 2019-10-03 16:25 UTC
3x Couldn't open ButterQuestTracker\Libs\Poncho-1.0\Poncho-1.0.xml
2x Couldn't open ButterQuestTracker\Libs\Sushi-3.0\Sushi-3.0.xml

```
1x ButterQuestTracker\Options-Options.lua:4: Cannot find a library instance of "TrackerHelper-1.0".
[C]: in function `error'
Atlas\Libs\LibStub\LibStub.lua:38: in function `LibStub'
ButterQuestTracker\Options-Options.lua:4: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "TrackerHelper-1.0"."
```

```
1x ...aceButterQuestTracker\ButterQuestTracker-1.9.0-beta.2.lua:6: Cannot find a library instance of "TrackerHelper-1.0".
[C]: in function `error'
Atlas\Libs\LibStub\LibStub.lua:38: in function `LibStub'
...aceButterQuestTracker\ButterQuestTracker-1.9.0-beta.2.lua:6: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "TrackerHelper-1.0"."
```

```
1x ...s\ButterQuestTracker\TrackerHelper\TrackerHelper.lua:3: Cannot find a library instance of "Poncho-1.0".
[C]: in function `error'
Atlas\Libs\LibStub\LibStub.lua:38: in function `LibStub'
...s\ButterQuestTracker\TrackerHelper\TrackerHelper.lua:3: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "Poncho-1.0"."
```

**Comment by cecilia-sanare** [comment] 2019-10-03 17:05
Ah, forgot to add it to the `.pkgmeta` dependencies file.

Thanks for the heads up!

**Comment by cecilia-sanare** [comment] 2019-10-03 17:18
This issue should now be resolved in [1.9.0-beta.3](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2801020).

Thanks for your continued support!

**Comment by Nillx** [comment] 2019-10-03 17:22
No problem :)

**Comment by Nillx** [comment] 2019-10-03 17:40
One new error with beta 3.


```
1x [ADDON_ACTION_BLOCKED] AddOn 'ButterQuestTracker' tried to call the protected function 'UIParent:SetHeight()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetHeight'
...s\ButterQuestTracker\TrackerHelper\TrackerHelper.lua:182: in function <...s\ButterQuestTracker\TrackerHelper\TrackerHelper.lua:168>
...s\ButterQuestTracker\TrackerHelper\TrackerHelper.lua:464: in function `Container'
...aceButterQuestTracker\ButterQuestTracker-1.9.0-beta.3.lua:491: in function `RefreshView'
...aceButterQuestTracker\ButterQuestTracker-1.9.0-beta.3.lua:113: in function `listener'
...ButterQuestTracker\QuestLogHelper\QuestLogHelper.lua:67: in function <...ButterQuestTracker\QuestLogHelper\QuestLogHelper.lua:65>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
InCombatSkipped
```

**Comment by cecilia-sanare** [comment] 2019-10-03 18:16
I'm unable to reproduce this, however I know where the issue is likely occuring.

If you disable your other addons does the issue go away?

**Comment by Nillx** [comment] 2019-10-03 18:30
Ill try to reproduce it again

**Comment by cecilia-sanare** [comment] 2019-10-03 18:31
I implemented a fix that should prevent this from occurring in [1.9.0-rc.1](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2801048).

**Comment by Nillx** [comment] 2019-10-03 18:33
Okey, ill post again if there are any errors.

**Closed as completed** 2019-10-04 03:30 UTC
Labels: bug
