### ISSUE TITLE
Quest tracking overrides are wiped out upon relogging

### ISSUE THREAD

**Issue by Nillx** [butter-cookie-kitkat/ButterQuestTracker#35] opened 2019-09-29 17:49 UTC
Im using 1.7.1 and im noticing that Hide Completed quests doesnt actually hide them. Or it works but when Automatic  track updated quests is OFF. 

Another tiny thing: Every time when i log in for the first time, the addon displays all of my current quests for some reason and i need to untrack them.

**Comment by cecilia-sanare** [comment] 2019-09-29 19:50
Hey @Nillx,

The way "Automatically Track Updated Quests" works in the same way as manually tracking a quest in your quest log.

Effectively it bypasses all of your filters in order to track the quest.
Hence why "Hide Completed Quests" has no impact on it.

The only "Filter" (it isn't really a filter, just a limit) that applies to these quests is the quest limit.

Also I can't reproduce your second issue, can you provide more details / screenshots?

**Comment by Nillx** [comment] 2019-09-29 21:32
I understand. 

As for the second "issue": addon auto starts tracking every quest in my quest log if i relog. I need to shift click and untrack all of them.

**Comment by Nillx** [comment] 2019-09-29 21:35
https://imgur.com/a/7iXTUXZ example before relogging and after relogging

**Comment by cecilia-sanare** [comment] 2019-09-30 00:56
Hey @Nillx, I'm able to reproduce this issue now. 

Thanks for taking the time to provide updates here!

**Comment by cecilia-sanare** [comment] 2019-09-30 01:21
This issue should now be resolved in [1.7.4](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2798693), let me know if you run into any issues!

**Closed as completed by cecilia-sanare** 2019-09-30 01:21 UTC
Labels: bug
