### ISSUE TITLE
weird flickering

### ISSUE THREAD

**Issue by Boomdead123** [butter-cookie-kitkat/ButterQuestTracker#26] opened 2019-09-26 18:29 UTC
## Bug description

I don't really know how to explain it but it keeps flashing on my screen

## Screenshots

![Issue](https://i.imgur.com/QTPLWBk.gif)

## Butter Quest Tracker Version

Newest version

**Comment by cecilia-sanare** [comment] 2019-09-26 18:51
Hey @Boomdead123!

By the newest version do you mean 1.7.0-rc.1 or do you mean 1.6.5?
If you're using 1.7.0-rc.1 can you update to 1.7.0-rc.2 and let me know if the issue persisist?

Thanks!

**Comment by Boomdead123** [comment] 2019-09-26 19:11
I was on the newest release version so 1.6.5 ill have to try out the beta version when I get home tonight

**Comment by Boomdead123** [comment] 2019-09-27 03:28
Got it fixed but looks like it was an issue with this addon and a quest tracker that questie has disabled it and working fine now

**Comment by cecilia-sanare** [comment] 2019-09-27 14:11
Awesome, thanks for your help in debugging this.

Just knowing it's linked to Questie's Tracker has helped tremendously in narrowing down where the issue is.

**This should now be resolved in [1.6.7](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2796627)!**

**Closed as completed** 2019-09-27 14:22 UTC
Labels: bug
