### ISSUE TITLE
Everytime I log in or reload the quest tracker is anchored to the wrong x coordinate.

### ISSUE THREAD

**Issue by mumblexgithub** [butter-cookie-kitkat/ButterQuestTracker#72] opened 2019-10-11 04:58 UTC
## Bug description

**Halfway through writing this I discovered it's a conflicting addon - not sure what though.
Is the tracker not anchored to UIParent? Nothing else is having this behaviour.**

EDIT: 4k monitor, UI scale 0.71, ElvUI (and other bits and pieces)

I want the tracker in the top left corner - and I can drag it there no problem but each UI reload changes the position. 
The manual x coord option in settings maxes out at about 2/3 the way left.  But this isn't even the position it resets to.
If I max out the tracker width I can _almost_ get it to touch the left side of my screen.

I don't recall the problem in the earlier version I had. 1.8.5 or something I think.

## Screenshots

![Wow_2019_10_11_17_38_36_626 (2)](https://user-images.githubusercontent.com/56423625/66625288-2099cd00-ec50-11e9-89d3-fada135c9099.jpg)
![Wow_2019_10_11_17_38_44_443 (2)](https://user-images.githubusercontent.com/56423625/66625296-24c5ea80-ec50-11e9-900c-cc1208e2054a.jpg)
![Wow_2019_10_11_17_38_49_518 (2)](https://user-images.githubusercontent.com/56423625/66625297-268fae00-ec50-11e9-8a2f-469e6b30390e.jpg)

**Butter Quest Tracker Version: 1.9.7-classic

**Comment by cecilia-sanare** [comment] 2019-10-11 06:15
Hey @mumblexgithub, yup the TrackerFrame is parented to UIParent.

Can you let me know which addon was conflicting with it?
It may help me figure out what exactly the issue is.

**Comment by cecilia-sanare** [comment] 2019-10-11 06:26
Ah, nevermind I figured it out.

Looks like ElvUI is adjusting the screen size after being loaded.

**Comment by cecilia-sanare** [comment] 2019-10-11 06:58
Hey @mumblexgithub, I just pushed out [1.9.8](https://www.curseforge.com/wow/addons/butter-quest-tracker/files/2806967) which includes a bug fix for this issue.

Let me know if you run into any other problems!

**Closed as completed by cecilia-sanare** 2019-10-11 06:58 UTC
Labels: bug

**Comment by Spiricore** [comment] 2019-10-11 07:59
Thanks, this solved my issue (#71) as well.

**Comment by mumblexgithub** [comment] 2019-10-11 08:42
Fixed in 2 hours.
How's that for service. 
Cheers.
